version: '3.8'
networks:
  {{ cookiecutter.project_package }}nwk:
    name: app
    driver: bridge
volumes:
  postgres_data:
    driver: local
services:
  {{ cookiecutter.project_slug }}:
    image: com.malli/{{ cookiecutter.project_slug }}:{{ cookiecutter.version}}
    container_name: {{ cookiecutter.project_slug }}
    ports:
      - "{{ cookiecutter.server_port }}:{{ cookiecutter.server_port }}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/{{ cookiecutter.db_name }}
      SPRING_DATASOURCE_PASSWORD: {{ cookiecutter.db_password }}
    networks:
      - {{ cookiecutter.project_package }}nwk
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: {{ cookiecutter.project_package }}db
    restart: always
    networks:
      - {{ cookiecutter.project_package }}nwk
    ports:
      - "{{ cookiecutter.db_port }}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: {{ cookiecutter.db_password }}
      POSTGRES_DB: {{ cookiecutter.db_name }}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: pg_isready -U postgres
      retries: 3